package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"net/mail"
	"strings"
	"time"

	"github.com/eldhosereji541/task-tracker-backend/internal/auth"
	"github.com/eldhosereji541/task-tracker-backend/internal/model"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	if strings.TrimSpace(input.Name) == "" {
		return nil, fmt.Errorf("name cannot be empty")
	}
	if _, err := mail.ParseAddress(input.Email); err != nil {
		return nil, fmt.Errorf("invalid email format")
	}
	if len(input.Password) < 8 {
		return nil, fmt.Errorf("password must be at least 8 characters")
	}

	hashedPassword, err := auth.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}

	user, err := r.TaskRepo.CreateUser(input.Name, input.Email, hashedPassword)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	token, err := r.TokenSvc.GenerateToken(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  *user,
	}, nil
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, storedPassword, ok := r.TaskRepo.GetUserByEmail(input.Email)
	if !ok || storedPassword == "" {
		return nil, fmt.Errorf("invalid credentials")
	}

	if !auth.CheckPasswordHash(input.Password, storedPassword) {
		return nil, fmt.Errorf("invalid credentials")
	}

	token, err := r.TokenSvc.GenerateToken(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User:  *user,
	}, nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	if strings.TrimSpace(input.Title) == "" {
		return nil, fmt.Errorf("title cannot be empty")
	}

	userID, ok := auth.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	now := time.Now()
	task := &model.Task{
		Title:       input.Title,
		Description: input.Description,
		Status:      *input.Status,
		Priority:    *input.Priority,
		CreatedAt:   now,
		UpdatedAt:   now,
		Deleted:     false,
		User:        &model.User{ID: userID},
	}

	return r.TaskRepo.CreateTask(task)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	userID, ok := auth.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	task, ok := r.TaskRepo.GetTaskByID(id)
	if !ok {
		return nil, fmt.Errorf("task not found")
	}
	if task.User == nil || task.User.ID != userID {
		return nil, fmt.Errorf("forbidden")
	}

	if input.Title != nil {
		if strings.TrimSpace(*input.Title) == "" {
			return nil, fmt.Errorf("title cannot be empty")
		}
		task.Title = *input.Title
	}
	if input.Description != nil {
		task.Description = input.Description
	}
	if input.Status != nil {
		task.Status = model.TaskStatus(*input.Status)
	}
	if input.Priority != nil {
		task.Priority = model.Priority(*input.Priority)
	}

	return r.TaskRepo.UpdateTask(task)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	err := r.TaskRepo.DeleteTask(id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, filter *model.TaskFilter) ([]*model.Task, error) {
	userID, ok := auth.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return r.TaskRepo.GetTasks(userID, filter)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	userID, ok := auth.GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	task, ok := r.TaskRepo.GetTaskByID(id)
	if !ok {
		return nil, nil
	}
	if task.User == nil || task.User.ID != userID {
		return nil, fmt.Errorf("forbidden")
	}
	return task, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
